services:
  db:
    image: mysql:latest
    container_name: mysql_menu_digital
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: feiraamizade_root
      MYSQL_DATABASE: feiraamizade_banco
      MYSQL_USER: feiraamizade
      MYSQL_PASSWORD: feiraamizade_password
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - web

  redis:
    image: redis/redis-stack:latest
    container_name: redis_menu_digital
    ports:
      - "6379:6379"       # Redis
    networks:
      - web

  app:
    build: .
    environment:
      RACK_ENV: production
      ROOT_LOGIN: "ADM"
      ROOT_PASSWORD: "changeme"
      DATABASE: "mysql"
      DATABASE_HOST: mysql_menu_digital
      DATABASE_USERNAME: feiraamizade
      DATABASE_PASSWORD: feiraamizade_password
      DATABASE_DB: feiraamizade_banco
      PRODUCTION: true
    expose:
      - "4567"
    depends_on:
      - redis
      - db
    networks:
      - web
  
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - web

volumes:
  mysql:

networks:
  web: