services:
  app:
    build: .
    container_name: menu_digital
    ports:
      - "4567:4567"
    depends_on:
      - redis
    volumes:
      - .:/app
    networks:
      - app_network

  redis:
    image: redis/redis-stack:latest
    container_name: redis_menu_digital
    ports:
      - "6379:6379"       # Redis
    networks:
      - app_network

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      # - '21:21' # FTP

    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - app_network
    
      
networks:
  app_network:
    driver: bridge
