services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: feira_amizade_2025
      MYSQL_DATABASE: feira_amizade_2025
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql